// Regenerates src/app/shared/icons.ts from every phosphor* name used in src/app and fails on unknown names.
// Usage: npm run icons              (write)
//        npm run icons -- --check   (exit 1 if the registry is out of date)
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const registry = 'src/app/shared/icons.ts';
const names = new Set();
const walk = (dir) => {
  for (const file of readdirSync(dir)) {
    const path = join(dir, file);
    if (statSync(path).isDirectory()) walk(path);
    else if (/\.(ts|html)$/.test(file) && !path.endsWith('icons.ts') && !file.endsWith('.spec.ts')) {
      for (const match of readFileSync(path, 'utf8').matchAll(/phosphor[A-Z][A-Za-z0-9]*/g)) names.add(match[0]);
    }
  }
};
walk('src/app');

const types = readFileSync('node_modules/@ng-icons/phosphor-icons/types/ng-icons-phosphor-icons-regular.d.ts', 'utf8');
const sorted = [...names].sort();
const unknown = sorted.filter((name) => !types.includes(`const ${name} =`));
if (unknown.length) {
  console.error('Unbekannte Icons:', unknown.join(', '));
  process.exit(1);
}

const list = sorted.map((name) => `  ${name},`).join('\n');
const output = `import {
${list}
} from '@ng-icons/phosphor-icons/regular';

/**
 * All icons used by the portal, registered once at the application root. Unregistered names render empty.
 * Generated by tools/sync-icons.mjs (npm run icons): do not edit by hand.
 */
export const APP_ICONS = {
${list}
};
`;

if (process.argv.includes('--check')) {
  if (readFileSync(registry, 'utf8').replace(/\r\n/g, '\n') !== output) {
    console.error('icons.ts ist veraltet. Bitte "npm run icons" ausführen.');
    process.exit(1);
  }
  console.log(`${sorted.length} Icons, Registry aktuell.`);
} else {
  writeFileSync(registry, output);
  console.log(`${sorted.length} Icons registriert.`);
}
